parameters:
    chewbacca_user.mailer.class: Chewbacca\UserBundle\Mailer\Mailer
    chewbacca_user.registration.form.handler.class: Chewbacca\UserBundle\Form\Handler\RegistrationFormHandler
    form.type.user_phone.class: Chewbacca\UserBundle\Form\Type\UserPhoneFormType

services:
    chewbacca_user.mailer:
        class: %chewbacca_user.mailer.class%
        arguments: [@mailer, @router, @templating, {confirmation.template: %fos_user.registration.confirmation.template%, resetting.template: %fos_user.resetting.email.template%, from_email: {confirmation: %fos_user.registration.confirmation.from_email%, resetting: %fos_user.resetting.email.from_email% }}]

    chewbacca_user.registration.form.handler:
        class: %chewbacca_user.registration.form.handler.class%
        scope: request
        arguments: [@fos_user.registration.form, @request, @fos_user.user_manager, @chewbacca_user.mailer]

    form.type.user_phone:
        class: %form.type.user_phone.class%
        arguments: []
        tags:
          - { name: form.type, alias: user_phone }