homepage:
    pattern:  /
    defaults: { _controller: ChewbaccaBackendCoreBundle:Default:index }
    
categories:
    pattern:  /categories
    defaults: { _controller: ChewbaccaBackendCoreBundle:Category:index }

categories_new:
    pattern:  /categories_new
    defaults: { _controller: ChewbaccaBackendCoreBundle:Category:new }