parameters:
#    chewbacca_sitemap.example.class: Chewbacca\SitemapBundle\Example

services:
#    chewbacca_sitemap.example:
#        class: %chewbacca_sitemap.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
