parameters:
    chewbacca_sitemap.generator_chain.class: Chewbacca\SitemapBundle\Services\SitemapGeneratorChain

services:
    chewbacca_sitemap.generator_chain:
        class: %chewbacca_sitemap.generator_chain.class%
        arguments: [ @router, { file_path: %kernel.root_dir%/../web/sitemaps.xml } ]
